# Generated by Django 6.0.2 on 2026-02-27 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="variation",
            options={"ordering": ["name"]},
        ),
    ]
