# Generated by Django 6.0.2 on 2026-03-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_options_alter_variation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="keywords",
            field=models.TextField(blank=True, null=True),
        ),
    ]
