# Generated by Django 6.0.2 on 2026-03-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="variation",
            name="name",
            field=models.CharField(max_length=256),
        ),
    ]
