# Generated by Django 6.0.2 on 2026-03-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_name_alter_variation_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AddField(
            model_name="product",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
