# Generated by Django 6.0.2 on 2026-03-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_options_product_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
