# Generated by Django 6.0.2 on 2026-02-25 02:51

import uuid

from django.db import migrations, models

import app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expansion",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("tcgcsv_id", models.CharField(max_length=32)),
            ],
            options={
                "abstract": False,
            },
            bases=(app.models.NameModel, models.Model),
        ),
        migrations.CreateModel(
            name="ExpansionProduct",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("tcgcsv_id", models.CharField(max_length=32)),
            ],
            options={
                "abstract": False,
            },
            bases=(app.models.NameModel, models.Model),
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("tcgcsv_id", models.CharField(max_length=32)),
            ],
            options={
                "abstract": False,
            },
            bases=(app.models.NameModel, models.Model),
        ),
    ]
