# Generated by Django 6.0.2 on 2026-03-12 02:33

import uuid

import django.db.models.deletion
from django.db import migrations, models

import app.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("tcgcsv_id", models.CharField(max_length=20)),
            ],
            options={
                "abstract": False,
            },
            bases=(app.utils.models.NameModel, models.Model),
        ),
        migrations.CreateModel(
            name="Expansion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("tcgcsv_id", models.CharField(max_length=20)),
                (
                    "game",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tcg.game"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(app.utils.models.NameModel, models.Model),
        ),
        migrations.CreateModel(
            name="Rarity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tcgcsv_name", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=64)),
                ("order", models.IntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tcg.game"),
                ),
            ],
            options={
                "ordering": ["game", "order"],
            },
            bases=(app.utils.models.NameModel, models.Model),
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tcgcsv_name", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=40)),
                ("order", models.IntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tcg.game"),
                ),
            ],
            options={
                "ordering": ["order"],
            },
            bases=(app.utils.models.NameModel, models.Model),
        ),
        migrations.CreateModel(
            name="ExpansionProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tcgcsv_id", models.CharField(blank=True, max_length=20, null=True)),
                ("number", models.PositiveIntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=256)),
                ("data", models.JSONField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "type_of",
                    models.CharField(
                        choices=[("SIN", "Cartas Sueltas"), ("SEA", "Producto Cerrado")],
                        default="SIN",
                        max_length=3,
                    ),
                ),
                (
                    "expansion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tcg.expansion",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tcg.game"),
                ),
                (
                    "rarity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tcg.rarity",
                    ),
                ),
                ("versions", models.ManyToManyField(blank=True, to="tcg.version")),
            ],
            options={
                "ordering": ["type_of", "game", "expansion", "number"],
            },
            bases=(app.utils.models.NameModel, models.Model),
        ),
    ]
