# Generated by Django 6.0.2 on 2026-03-12 02:41

import uuid

import django.db.models.deletion
from django.db import migrations, models

import app.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_keywords"),
        ("tcg", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TCGProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "expansion_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="tcg.expansionproduct",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="tcg.game",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tcgproduct",
                        to="products.product",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tcg.version"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(app.utils.models.NameModel, models.Model),
        ),
    ]
