# Generated by Django 6.0.2 on 2026-03-12 03:18

import uuid

import django.db.models.deletion
from django.db import migrations, models

import app.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_keywords"),
        ("tcg", "0002_tcgproduct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tcgproduct",
            name="game",
        ),
        migrations.RemoveField(
            model_name="tcgproduct",
            name="version",
        ),
        migrations.CreateModel(
            name="TCGVariation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "tcg_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variations",
                        to="tcg.tcgproduct",
                    ),
                ),
                (
                    "variation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tcgproduct",
                        to="products.variation",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tcg.version"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(app.utils.models.NameModel, models.Model),
        ),
    ]
