# Generated by Django 6.0.2 on 2026-03-12 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcg", "0003_remove_tcgproduct_game_remove_tcgproduct_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tcgproduct",
            name="expansion_product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tcgproduct",
                to="tcg.expansionproduct",
            ),
        ),
    ]
